# Generated by Django 4.1.1 on 2022-09-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_remove_library_authorname_library_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='category',
        ),
        migrations.RemoveField(
            model_name='author',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='author',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='library',
            name='publicationid',
        ),
        migrations.RemoveField(
            model_name='library',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='library',
            name='studentname',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='bookid',
            field=models.IntegerField(blank=True, null=True, verbose_name=5),
        ),
        migrations.AddField(
            model_name='library',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blog/app/media/Library'),
        ),
        migrations.AddField(
            model_name='library',
            name='is_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='library',
            name='booktitle',
            field=models.CharField(max_length=250),
        ),
    ]
